import os
import json

china_traffic_handbook = """S1 Driving side & lane discipline: In mainland China you drive on the right. As a default, vehicles keep to the right unless road markings/signs say otherwise; move left to overtake or to position for a left turn, then return when safe. Where the road is divided into motor-vehicle lanes, non-motor-vehicle lanes, and sidewalks, each category must use its designated part of the road.

S2 Speed limits are in km/h (not mph). Always follow posted limit signs and lane-specific markings. On expressways, passenger vehicles commonly operate up to 120 km/h where permitted; urban roads usually have lower signed limits depending on road class, geometry, and local conditions.

S3 Traffic lights (vehicles): Standard signals are red, yellow, and green. Red means stop, green means go, and yellow means stop if it is safe to do so; vehicles that have already crossed the stop line may continue. Flashing yellow means proceed with caution after checking for safety. If a traffic police officer is directing traffic, the officer’s instructions override the lights.

S4 Right turn on red: In mainland China, a vehicle may generally turn right on red unless a specific red arrow, sign, marking, or lane-control signal prohibits that movement. Even when right turn on red is allowed, the driver must yield to pedestrians and other lawfully moving traffic and must not force through the turn.

S5 Signalised intersections & turning priority: At signalised intersections, enter the correct guide lane early for your intended movement. Turning vehicles must not obstruct released straight-through traffic or pedestrians. Where opposing movements conflict, right-turning vehicles typically yield to opposing left-turning vehicles already lawfully proceeding.

S6 Unsignalised intersections: At intersections without signals or police control, first slow down and observe. If signs or markings are present, follow them. If there is no priority control, yield to traffic approaching from your right; turning vehicles must also yield to straight-through traffic already proceeding through the intersection.

S7 Roundabouts: At roundabouts, vehicles entering must give way to vehicles already circulating within the roundabout. Choose the correct lane early according to your intended exit and do not force entry into the circulating flow.

S8 Pedestrian crossings: A motor vehicle approaching a crosswalk must slow down. If pedestrians are crossing, the vehicle must stop and yield. At intersections, turning vehicles must also yield to pedestrians who are lawfully crossing the road into which the vehicle is turning.

S9 Non-motor vehicle lanes: Many urban roads in China have dedicated lanes for bicycles and electric bicycles. Motor vehicles must not drive in, stop in, or occupy these lanes unless markings explicitly permit it. Drivers must anticipate frequent interaction with bicycles, e-bikes, and scooters near junctions and curbside areas.

S10 Electric bicycles & mixed traffic: Electric bicycles are a major part of mainland China’s road environment and are typically treated under non-motor-vehicle rules when compliant with the legal standard. They commonly use non-motor-vehicle lanes and may appear in large numbers at junctions, crossings, and roadside access points; drivers should expect dense mixed traffic and yield where required.

S11 Yellow box junctions / keep-clear areas: A yellow criss-cross box marking means do not enter unless your exit is clear. Do not stop and wait inside the box, and do not enter an occupied intersection in a way that blocks cross traffic. This rule is especially important in dense urban traffic.

S12 Queueing, merging & lane changes: When traffic is queued or moving slowly, drivers must not force lane changes, cut into queues aggressively, or use opposing lanes to bypass congestion. A vehicle changing lanes must not affect the normal movement of vehicles already in the target lane.

S13 Dedicated lanes & special-use lanes: Roads may include lanes reserved for buses, non-motor vehicles, turning movements, or other special uses. Only the permitted class of traffic may use such lanes during the signed times and conditions. Always check lane arrows, overhead signals, roadside signs, and pavement text.

S14 Expressways / motorways: Expressways in mainland China are controlled-access roads. Use ramps to enter and exit, yield when merging, and do not reverse, make U-turns, or drive the wrong way. The emergency lane must not be used except for emergencies or as specifically directed by authorities.

S15 Emergency vehicles & enforcement: Police cars, fire engines, ambulances, and other emergency vehicles on urgent duty have priority and may use sirens/lights to request immediate passage; other road users must yield. Traffic enforcement in mainland China also relies heavily on cameras and automated monitoring, so violations such as red-light running, speeding, and illegal lane use are commonly detected electronically.

S16 Driver behavior rules: In mainland China, a driver must not make or answer a hand-held phone call, watch video, or engage in any other act that impedes safe driving; hands-free use is not expressly banned nationwide, but it can still be penalized if it affects control of the vehicle. Safety helmets are mandatory nationwide for motorcycle riders and passengers; helmet rules for electric bicycles are mainly set by local regulations, not a single national rule. For ordinary private-car drivers, blood alcohol of 20 mg per 100 ml of blood or more is illegal: 20-79 mg/100 ml is drink-driving, and 80 mg/100 ml or more is drunk driving. Drivers must obey local no-horn signs and silence zones, common in urban areas, and should use the horn only as a warning where visibility is poor, such as blind bends, narrow mountain roads, tunnels, or some unsignalled crossings. High beam must be dipped within 150 m of oncoming traffic, when following closely, and on well-lit urban roads; daytime running lights are not generally mandatory for private cars.

S17 Vehicle registration plates: Ordinary privately owned small cars in mainland China normally use blue plates with white characters on both the front and rear; this is the standard civilian plate most drivers will see, although new-energy cars use green plates and some other vehicle classes use different colors. The registration uses mixed scripts: the first character is a Chinese abbreviation for the province-level region, followed by a Latin letter for the city or prefecture-level issuing authority, and then five alphanumeric characters. The usual pattern is therefore one Chinese character + one Latin letter + five letters/digits, with the final five forming the vehicle’s serial combination under that local office. For layout, standard car plates are long, single-line plates without an EU-style country strip; the province character and city letter at the start act as the main regional identifier, and the same registration number is shown front and rear.

S18 Sign system & visual cues: Regulatory signs in mainland China follow GB 5768 conventions: prohibitions are usually circular with a red border, white background and black symbol (often crossed by a red slash), while mandatory instructions are circular blue signs with white arrows or symbols; common examples include no entry, no parking and turn-right-only. Warning signs are generally yellow equilateral triangles with a black border and black symbol, so hazards such as bends, merging traffic or pedestrian activity are shown in a yellow warning triangle rather than a yellow diamond. The STOP sign is an octagonal red sign with a white border, normally marked with the Chinese character “停” (sometimes with “STOP”). Yield / give-way is usually an inverted triangle with a red border and white centre, commonly reading “减速让行”. School or children hazards are shown by a yellow triangular warning sign with child figures or “注意儿童”; there is no single nationwide school-zone default speed, so obey any posted reduced limit and markings outside schools.

S19 Road & pavement markings: In mainland China, yellow longitudinal lines separate opposing traffic, while white lines separate lanes moving in the same direction. Solid lines mean you must not cross them; with a double line, crossing is prohibited, and where one side is solid and the other broken, only traffic on the broken side may cross when safe. Road edges and shoulders are normally marked by white edge lines, usually solid on expressways and major roads, turning dashed near merges, exits, or other places where vehicles are allowed to cross the edge. No-overtaking sections are commonly shown by double solid yellow centerlines; double solid white lines are used between same-direction lanes or channelised areas to prohibit lane changes or crossing. Special pavement wording is common: bus-only lanes are usually marked with the Chinese characters “公交专用道”, often with a bus symbol and operating times on adjacent signs. Crosswalks are zebra crossings made of broad white transverse bars, and approaches often have white diamond warning markings in the lane before the crossing.

S20 Tolls & special infrastructure: Mainland China’s expressways use a national ETC system: vehicles fitted with an ETC on-board unit linked to an ETC card or bank account use signed ETC lanes, while MTC/manual lanes remain for non-ETC vehicles. Expressway tolls are charged mainly by vehicle category and distance; since 2020, trucks are charged by class (chiefly by axle number/type) and distance rather than by weighing at the toll booth. Near schools, there is no single nationwide school-zone speed limit, so obey the posted local limit—commonly 30 km/h at school entrances—together with children/school warning signs, zebra crossings, flashing amber beacons where installed, and pavement legends such as “学校” or “前方学校.” Reserved bus lanes are marked by roadside signs and lane text such as “公交专用道”; the sign specifies the operating hours. Do not enter a bus lane during its posted hours except where signs or broken-line markings permit crossing for a turn, and do not impede buses pulling out from marked stops."""
