import os
import json

japan_traffic_handbook = """S1 Driving side & lane discipline: In Japan you drive on the left. As a default, keep left unless road markings/signs say otherwise; move out to overtake, to turn right, or to pass an obstruction, then return to the left when safe.

S2 Speed limits are in km/h (not mph). Unless signed otherwise, regular-sized automobiles must obey default speed limits of 60 km/h on ordinary roads and 100 km/h on expressways. Always follow posted limit signs and road markings where they are provided.

S3 Traffic lights (vehicles): Standard signals are green, yellow, and red. Green permits through movement and turning for ordinary motor vehicles. Yellow means stop unless you are already too close to stop safely. Red means stop at the stopping point.

S4 Turn on red / arrow signals: There is no general “turn on red” permission in Japan. A vehicle must not proceed past the stopping point on red unless it is already in the process of completing a lawful turn through the intersection. A green arrow permits movement in the indicated direction even if the main signal is red or yellow.

S5 Left-turn and right-turn behaviour at signals: In left-hand traffic, left turns are usually the simpler near-side turn, while right turns typically cross opposing traffic and may require waiting within the intersection for a safe gap. A vehicle already making a right turn must not obstruct traffic approaching on a green light.

S6 Two-stage right turn for light vehicles / mopeds: Lightweight vehicles such as bicycles, and mopeds where two-stage right turn rules apply, do not make a direct sweeping right turn like a car. Instead, they proceed straight to the far side, stop at the turning point, reorient, and wait for the next release to complete the right turn.

S7 “Stop” / “Slow down” control: At a STOP sign or stop line, make a full stop before proceeding. Japan’s STOP sign is visually distinctive: an inverted red triangle rather than the octagonal design common in many other countries. “Slow down” control also appears as a specific sign and requires reduced speed and caution.

S8 Railway crossings: A major Japan-specific rule is that drivers must stop before a railway crossing (or before the stop line if there is one), check both directions, and proceed only when safe. If the crossing is controlled by traffic lights, pass in accordance with the lights. Do not enter unless there is space to clear the tracks fully.

S9 Pedestrian crossings: Pedestrians have right-of-way on pedestrian crossings. Drivers must slow down when approaching a pedestrian crossing or bicycle crossing lane unless it is clearly empty, and must stop and yield when pedestrians or cyclists are crossing or about to cross.

S10 No overtaking near crossings: Do not overtake a vehicle that is stopped at or immediately before a pedestrian crossing or bicycle crossing lane. Drivers must also not overtake another vehicle and then cut in across a crossing, or within 30 meters before such a crossing.

S11 Parking / stopping near crossings: Drivers must not stop or park on a pedestrian crossing or bicycle crossing lane, or within the restricted area around it, except when stopping for a red light or to avoid danger. Watch carefully for posted “No parking” and “No stopping” signs.

S12 Expressways (motorways): Expressways are controlled-access roads. Use the acceleration lane to build speed before merging, yield appropriately when joining, and use the passing lane only for overtaking. Do not drive on the shoulder except in emergencies.

S13 Lane use on expressways: On expressways, stay in the normal driving lane as your default lane and use the passing lane only when overtaking. Do not cruise continuously in the passing lane, and do not weave between lanes unnecessarily.

S14 Vulnerable road users: Expect frequent interaction with pedestrians and cyclists, especially in urban areas and around crossings. Drivers must yield at pedestrian crossings and should watch carefully when turning at intersections, because pedestrians and bicycles may be crossing even when motor traffic also has a green signal.

S15 Sign system note: Road signs in Japan are standardized nationally. For visual recognition tasks, two especially distinctive features are the inverted triangular STOP sign and the prominence of dedicated signs for controls such as “slow down,” “no parking,” “no stopping,” railway crossings, and exclusive lanes.

S16 Driver behavior rules: In Japan, using a hand-held mobile phone while driving is prohibited: you must not hold a phone for calls, texting, or other operation, and you must not stare at its screen; hands-free use is not expressly banned but is unlawful if it interferes with safe driving, and penalties are much heavier if phone use creates danger or causes a crash. Helmets are mandatory nationwide for both the rider and any passenger on motorcycles and mopeds, with no general adult exemption. For ordinary drivers, alcohol offences are commonly enforced by breath alcohol: 0.15 mg per litre of breath or more (about 0.03% BAC) is punishable, and driving while impaired can be punished even below that level. The horn may be used only when necessary to avert danger or where a blue “sound horn” sign requires it; unnecessary honking is not allowed. At night, use headlights; high beam is the default on dark roads, but switch to low beam for oncoming traffic, when following another vehicle, and where lighting or conditions make high beam unnecessary. Daytime running lights are not generally mandatory for ordinary cars.

S17 Vehicle registration plates: Standard private passenger cars in Japan normally display white plates with green characters at both the front and rear; the familiar yellow plates are for kei cars, not ordinary private cars. Ordinary Japanese plates use mixed scripts rather than Latin-only text: the upper line shows the registration office or regional name in kanji, while the lower line includes one hiragana character and Arabic numerals. The usual format is [region name] [classification number, now usually three digits] on the top line, then [hiragana] [four-digit serial number] with a centered dash below; if a serial begins with zero, the unused leading position may be shown as a centered dot. Plates are typically arranged in a two-line layout, with the region identifier at the upper left and no EU-style country strip. Front and rear carry the same number, and the rear plate commonly bears an official seal over a mounting bolt.

S18 Sign system & visual cues: In Japan, most regulatory signs are circular. Prohibitions and restrictions are usually white with a red border, such as speed-limit signs; no-entry is a red disc with a white horizontal bar; and no-parking/no-stopping use a blue disc with a red border and red slash or cross. Mandatory instructions are blue circles with white arrows or symbols for required direction, turn, or lane use. Warning signs are yellow diamonds with black symbols, so curves, intersections, railway crossings, pedestrian crossings, and children are shown on yellow diamond boards rather than red-bordered triangles. The STOP sign is a red inverted triangle with a white border and white 止まれ; newer signs often also show small English “STOP.” Japan does not generally use a separate European-style GIVE WAY sign; yielding is commonly indicated by white triangular road markings, and some locations use an inverted white triangle with a red border marked 徐行 (“slow”), requiring a slow approach and yielding as necessary. There is no nationwide school-zone speed limit; lower limits apply only where posted, including many 30 km/h Zone 30 areas.

S19 Road & pavement markings: In Japan, the centre line between opposing traffic is usually white if crossing is permitted when safe; a solid yellow line (often appearing orange) means you must not cross or straddle it, so do not overtake across it or move onto the opposing side. Two solid centre lines, or a solid double line/hatched median, mark a separation that must not be crossed. Lane-edge lines are normally white: a solid white line marks the edge of the carriageway or shoulder, while broken white edge lines appear where vehicles may legally enter or leave the edge area, such as at junctions, bays, or merges. Japan does not generally use the North American double-yellow no-passing system; the standard no-crossing/no-overtaking marking is the single solid yellow centre line, though double solid white lines may also be used for strong separation. Road text is usually in Japanese, for example 「止まれ」 before a stop line and 「バス専用」 or 「専用」 for bus-only lanes; HOV diamonds and Chinese wording such as 「公交专用道」 are not Japanese markings. Crosswalks are zebra crossings with broad white bars, often preceded by white diamond warning markings.

S20 Tolls & special infrastructure: On expressways, Japan’s standard electronic toll system is ETC: vehicles use an in-car ETC onboard unit with an ETC card, and toll plazas are signed for ETC-only lanes or mixed ETC/general lanes. Around schools, Japan does not use one nationwide US-style flashing school-zone beacon format; instead, local authorities commonly sign school routes (通学路) and children crossings, use colored or painted road surfaces and warning markings, and often apply 30 km/h “Zone 30” limits or time-based vehicle restrictions near schools. Reserved bus lanes are marked by roadside signs and lane text such as バス専用 (bus only) or バス優先 (bus priority), with any operating hours shown on the sign; during the stated times other vehicles must stay out of bus-only lanes, while in bus-priority lanes they may enter only if they do not obstruct buses and should yield to buses pulling back into traffic."""
