import os
import json


uk_traffic_handbook = """S1 Driving side & lane discipline: In the UK you drive on the left. As a default, keep left unless road markings/signs say otherwise; move out to overtake, to turn right, or to pass an obstruction, then return to the left when safe.

S2 Speed limits are in mph (not km/h). Unless signed otherwise, typical “national speed limit” defaults are 70 mph on motorways/dual carriageways and 60 mph on single carriageways, while built-up areas are commonly 30 mph (and widely 20 mph zones exist in many places). Always follow posted limit signs and the national speed limit symbol where used.

S3 Traffic lights (vehicles): Standard UK sequence is red → red+amber (get ready, still stop) → green → amber (stop unless unsafe). There is no general “turn on red” permission—treat a red signal as stop unless a separate permitted movement is explicitly shown.

S4 Green filter arrows at signals: A green arrow indicates a permitted movement for a specific lane/direction (a “filter”). Only enter that lane if you intend to go that way, and proceed only in the arrow’s direction when it is lit (even if other movements are held).

S5 Roundabouts: Modern UK-style roundabouts use the “priority rule”: traffic entering must give way to traffic already circulating. In left-hand traffic this generally means giving way to vehicles approaching from your right; choose the correct lane early and signal on exit.

S6 “Give Way” / “Stop” control: At many junctions you’ll see a GIVE WAY sign and/or an inverted triangle road marking with broken white lines—yield to traffic on the main road. A STOP sign and solid stop line require a full stop before proceeding.

S7 Zebra/parallel crossings (uncontrolled): Zebra crossings are marked with black-and-white stripes and Belisha beacons. Drivers should be prepared to slow/stop for pedestrians waiting, and must give way once a pedestrian has stepped onto the crossing. Do not overtake the vehicle nearest a crossing (especially if it has stopped).

S8 Signal-controlled pedestrian crossings: Pelican, puffin, toucan and related crossings use red/green “man” signals for pedestrians with push-buttons. Pelican crossings are distinctive because after the vehicle red phase, a flashing amber may allow vehicles to proceed if the crossing is clear; puffin/toucan crossings do not use a flashing amber phase and instead follow a standard traffic-light style sequence.

S9 Box junctions (“yellow boxes”): A criss-cross yellow box means “don’t enter unless your exit is clear.” Exception: you may enter and wait if you are turning right and are only blocked by oncoming traffic or other right-turning vehicles; at signalled roundabouts, do not enter the box unless you can fully clear it without stopping.

S10 Yellow-line parking/waiting rules: Double yellow lines mean no waiting at any time (subject to signed exceptions). Single yellow lines restrict waiting during times shown on nearby plates or zone-entry signs. Short yellow kerb marks (“blips”) add loading/unloading restrictions—check signs.

S11 Red routes (where used): Red lines along the kerb indicate stronger “no stopping” controls than yellow lines. Double red lines mean no stopping at any time; single red lines apply during signed times. Only stop in specifically marked bays/boxes when permitted by accompanying signs.

S12 Motorways basics: Motorways are controlled-access roads—no pedestrians/cyclists and no at-grade junctions; you join via a slip road and must give priority to motorway traffic. Use the left lane as your default cruising lane and overtake to the right; do not weave.

S13 Hard shoulder / emergency areas / overhead control: Do not use a hard shoulder except in an emergency or when directed by signs/authorities. On some motorways the hard shoulder may be opened as a running lane only when overhead signs show it is open; a red ‘X’ indicates a closed lane that must not be used. Use emergency areas only for emergencies and follow SOS signage.

S14 Bus lanes & bus gates: Many UK cities use bus lanes (and “bus gates”) reserved for buses (often also cycles and sometimes taxis) during signed hours; entering when not permitted is an offence. Look for carriageway text (e.g., “BUS LANE” / “BUS GATE”) and regulatory signs.

S15 Vulnerable road users & junction priority: Expect frequent interaction with pedestrians, cyclists, and (in some areas) horses. Give extra space when overtaking vulnerable road users; at junctions, give way to pedestrians crossing or waiting to cross the road you are turning into/from, and respect cyclist advanced stop lines at signals (stop behind the first line on red/amber).

S16 Driver behavior rules: It is illegal to hold and use a hand-held mobile phone or sat-nav while driving in the UK, even when stopped at traffic lights or in slow traffic; hands-free use is permitted only if it does not distract you. Motorcycle and moped riders, and pillion passengers, must wear an approved safety helmet nationwide. The drink-drive limit for ordinary private-car drivers is 80 mg of alcohol per 100 ml of blood in England, Wales and Northern Ireland, but 50 mg/100 ml in Scotland. Do not sound the horn while stationary on the road, and in built-up areas you must not use it between 11:30 pm and 7:00 am except when another road user is a danger. Use full beam only on dark, unlit roads; dip your headlights for oncoming traffic, when following another vehicle, and whenever full beam could dazzle. Daytime running lights are common on newer vehicles, but they do not replace dipped headlights in poor visibility.

S17 Vehicle registration plates: Standard UK private cars display black characters on a white reflective plate at the front and on a yellow reflective plate at the rear. The registration mark itself uses only Latin letters A–Z and Arabic numerals 0–9 in the prescribed Charles Wright style; other scripts are not used in legal registration marks. In Great Britain, most vehicles first registered since 1 September 2001 use the format AB12 CDE: the first two letters are the local memory tag, the two digits are the age identifier (changing on 1 March and 1 September, for example 24 and 74 in 2024), and the last three letters are random. Northern Ireland uses a separate format, typically ABC 1234, with no age identifier. Car plates are usually a single line, but a two-line plate is permitted where the mounting space is square or narrow. An optional left-hand band may show an approved national flag and identifier; for international use, only a UK identifier with the Union Flag replaces a separate country sticker.

S18 Sign system & visual cues: In the United Kingdom, most regulatory signs are circular: a red ring shows a prohibition or restriction (for example speed limits, no entry, no right turn), while a blue circle gives a mandatory instruction such as turn left or pass on a particular side. Warning signs are normally red-bordered triangles with a white background, not yellow diamonds; direction and information signs are instead usually rectangular, with blue used for motorways and green for primary routes. The STOP sign is the standard red octagon with white capital letters “STOP”, and the same word is usually painted on the road at the stop line. Give-way control is shown by an inverted white triangle with a red border, often reinforced by “GIVE WAY” road markings and a broken give-way line. School or children warnings use a red-bordered triangle showing children, and there is no unique nationwide “school zone” sign style; around schools, signed 20 mph limits or timed 20 mph zones are common, sometimes with flashing amber lamps.

S19 Road & pavement markings: In the UK, centre and lane markings are generally white, not yellow: opposing traffic is usually separated by broken white centre lines, while double white lines mean extra restriction. If the line nearest you is solid, you must not cross or straddle it except for limited Highway Code exceptions; if your side is broken, you may cross when safe. Lane and carriageway edges are also marked in white: lanes in the same direction are divided by short broken white lines, hazard warning lines use longer, closer dashes, and many higher-speed roads have a solid white edge line at the nearside. Do not confuse centre-line rules with kerbside double yellow lines, which mean no waiting at any time; UK “no overtaking” is primarily shown by double white centre lines. Special road text commonly includes BUS LANE, BUS STOP and cycle-lane symbols. Zebra crossings are wide black-and-white stripes, usually with Belisha beacons and zig-zag approach markings where stopping, parking and overtaking are prohibited.

S20 Tolls & special infrastructure: The United Kingdom has no nationwide electronic toll tag system: most roads are free, and charged crossings or local schemes use their own arrangements. A common example is the barrier-free Dart Charge at the Dartford Crossing, which must be paid by midnight the day after travel online, by phone, or via a local account; elsewhere, some toll bridges, tunnels, and congestion-charge areas use separate payment systems. Near schools, watch for 20 mph limits or 20 mph zones, amber flashing “wig-wag” lights at school times, and yellow zig-zag “SCHOOL KEEP CLEAR” markings; stopping on the zig-zags is prohibited during the times shown or while the lights operate. Bus lanes are marked with blue roadside signs and carriageway legends such as “BUS LANE,” with the sign stating permitted vehicle types and operating hours; outside those hours, general traffic may use the lane unless signing says otherwise. In built-up areas, give priority to buses signalling to pull away from stops."""