import os
import json

us_traffic_handbook = """S1 Driving side & lane discipline: In the United States you drive on the right. As a default, keep right on two-way roads unless markings/signs say otherwise; move left to overtake, to position for a left turn, or to avoid an obstruction, then return to the right when safe.

S2 Speed limits are in mph (not km/h). There is no single nationwide default speed limit for all roads; limits vary by state, road type, and local conditions. Always follow posted limit signs, and expect lower signed speeds in school zones, work zones, residential streets, and other special areas.

S3 Traffic lights (vehicles): Standard signals are green, yellow, and red. Green permits movement subject to yielding where required; yellow means stop if you can do so safely; red means stop at the stop line, before the crosswalk, or before entering the intersection. A flashing red signal is treated like a STOP sign, while a flashing yellow signal means proceed with caution.

S4 Turn on red: A major U.S. feature is that right turn on red is generally permitted after a full stop unless a sign prohibits it, but this varies by state and locality. Even where allowed, the driver must yield to pedestrians, cyclists, and other traffic with the right-of-way. Do not assume that a red arrow allows the turn; red-arrow rules vary and are often more restrictive.

S5 All-way stop / four-way stop: All-way stop intersections are especially common in the U.S. Every approaching vehicle must come to a full stop. The first vehicle to arrive generally goes first; if two vehicles arrive at the same time, the vehicle on the right typically has priority. When opposite vehicles arrive together, a left-turning vehicle normally yields to an oncoming vehicle going straight.

S6 STOP / YIELD control: At a STOP sign, stop at the stop line; if there is no stop line, stop before the crosswalk or before entering the intersection where you can see safely. At a YIELD sign, slow down and give way to conflicting traffic and pedestrians before proceeding.

S7 Pedestrian crossings & turning priority: Drivers must yield to pedestrians in crosswalks. At many intersections, this includes marked crosswalks and also unmarked crosswalks implied by the intersection geometry under state law. Turning vehicles must not cut across pedestrians who are lawfully crossing.

S8 School buses: School-bus rules are a major U.S.-specific feature. Yellow flashing lights mean the bus is preparing to stop, so slow down and prepare to stop. Red flashing lights with an extended stop arm mean you must stop and remain stopped until the lights stop flashing, the stop arm is withdrawn, and the bus begins moving. On undivided roads, traffic in both directions generally must stop; on divided highways, opposing traffic often does not need to stop, depending on state law and roadway separation.

S9 Freeways / Interstates: U.S. freeways and Interstates are controlled-access roads. Use ramps to enter and exit, accelerate on the entrance ramp, and yield to freeway traffic when merging. Use the right lanes for ordinary travel and the left lanes mainly for overtaking, unless local signs or lane controls specify otherwise.

S10 HOV / carpool / managed lanes: Many U.S. urban highways use HOV or managed lanes reserved for vehicles meeting posted occupancy or toll requirements. These lanes are commonly marked by a white diamond symbol and/or HOV wording. Always check the posted occupancy requirement, hours of operation, and entry/exit restrictions.

S11 Lane-control signals / reversible lanes: Some roads use overhead lane-control signals. A green downward arrow means the lane is open for travel; a red X means the lane is closed and must not be used. On roads with reversible or actively managed lanes, follow overhead signals and signs rather than assuming the lane direction from memory.

S12 Two-way center left-turn lanes: A common U.S. road feature is the shared center left-turn lane on multi-lane roads. Use it only for left turns or, where permitted, short setup movements into driveways or side streets. Do not use it as a through lane, passing lane, or waiting lane for general travel.

S13 Railroad crossings: At railroad crossings, obey flashing lights, bells, gates, signs, and pavement markings. Stop behind the stop line or before the tracks when required, and do not enter unless you can clear the tracks completely. Never drive around or under a lowered gate.

S14 Emergency vehicles & roadside incidents: When an emergency vehicle approaches with siren/lights, pull to the right and stop unless directed otherwise. Many states also have “move over” or slow-down laws for stopped emergency, service, or disabled vehicles on the roadside, so check local law and follow posted requirements.

S15 Sign system note: U.S. road signs are largely standardized through the MUTCD. For visual recognition, common clues include the octagonal STOP sign, the triangular YIELD sign, yellow diamond warning signs, school-zone signs, white regulatory speed-limit signs in mph, and white diamond markings/signs for HOV or carpool lanes.

S16 Driver behavior rules: For ordinary drivers, the United States has no nationwide ban on mobile-phone use while driving; hand-held calling and texting are regulated mainly by state law, while hands-free use is usually allowed where restrictions exist. A specific federal rule applies to commercial motor vehicle drivers, who may not use hand-held mobile phones or text while driving. Motorcycle and moped helmet requirements are not nationwide: each state sets its own rules, and coverage may differ for motorcycles, mopeds, riders, and passengers; some states require helmets for all, others only for younger or less-experienced riders, and a few have no general motorcycle helmet mandate. The per se BAC limit for ordinary private-car drivers is 0.08% in every state except Utah, where it is 0.05%. State laws generally require a working horn and allow its use only when reasonably necessary for safety; unnecessary honking, and some local no-honking or quiet zones, can be penalized. High beams must be dimmed for oncoming traffic and when closely following another vehicle under state distance rules; daytime running lights are permitted but not federally required.

S17 Vehicle registration plates: The United States has no nationwide private-car plate design or numbering system. Plates are issued by each state and the District of Columbia, and standard passenger plates usually have a reflective background with dark letters, but colors, slogans, and graphics differ widely. If a state requires two plates, matching plates with the same number are displayed front and rear; other states require only a rear plate. The usual plate size is the North American 12 × 6 in (305 × 152 mm) single-line format, although motorcycles and some special classes use smaller plates. Passenger serials use only Latin letters and Arabic numerals, with state names and optional slogans in the Latin alphabet; ordinary plates do not use non-Latin scripts. Serial patterns are set by the issuing state, commonly 5 to 7 characters, such as ABC-1234, 123-ABC, or variants with separators. Most ordinary passenger plates do not include a mandatory region code in the serial itself, though some states print county names, use registration stickers, or reserve certain serial blocks for vehicle classes.

S18 Sign system & visual cues: U.S. signs follow the Manual on Uniform Traffic Control Devices (MUTCD). Regulatory signs—the “must do” or prohibition signs—are usually white with black lettering or symbols, most often rectangular, for example SPEED LIMIT, KEEP RIGHT, NO TURN ON RED, and lane-use-control signs; prohibitions may also use red, such as a red circle-and-slash symbol or the red-and-white DO NOT ENTER sign. Warning signs are generally yellow diamonds with black symbols or text (curve, merge, signal ahead, deer crossing), not the red-bordered triangular warning signs common in many countries. The STOP sign is always a red octagon with a white border and the word STOP in English. The YIELD sign is a downward-pointing triangle with a red border, white center, and red YIELD legend. School-area warnings typically use fluorescent yellow-green signs, especially the pentagon-shaped SCHOOL sign with child symbols; school speed limits are shown on white regulatory signs in mph and apply only under the posted conditions, such as stated times, flashing beacons, or when children are present.

S19 Road & pavement markings: In the United States, yellow centerlines separate opposing traffic and white lines separate lanes moving in the same direction. A broken yellow centerline may be crossed to pass when sight distance is clear; if the line on your side is solid, do not pass; a solid-and-broken pair allows passing only from the broken-line side; and double solid yellow means no passing in either direction, except to turn left into or out of a driveway, alley, or intersection where permitted. Lane-edge lines are typically solid white on the right edge of the roadway and solid yellow on the left edge of a divided highway or one-way roadway. Dashed white lines are used where lane lines or edge guidance continue through merges, exits, or lane drops. Double solid white lines separate same-direction lanes where lane changes are prohibited. Pavement words and symbols are usually white: ONLY marks turn-only lanes; BUS ONLY or BUS LANE marks transit lanes; and a white diamond marks HOV/carpool lanes. Crosswalks are marked in white, commonly as two transverse lines or high-visibility ladder/continental bars; no single zebra pattern is required nationwide.

S20 Tolls & special infrastructure: The United States has no single national toll tag. Electronic toll collection is common on toll roads, bridges, and tunnels; E‑ZPass is the main multi‑state system in the East and Midwest, while other regions use systems such as SunPass in Florida and FasTrak in California. Many facilities are now cashless, requiring either a compatible transponder or toll‑by‑plate billing sent to the registered owner. School zones are typically marked with fluorescent yellow‑green SCHOOL or school‑crossing signs and often a reduced speed limit; that lower limit applies only as stated on the sign, such as during posted hours, on school days, or when amber beacons flash. Pavement markings often include “SCHOOL” and marked crosswalks. Reserved bus or transit lanes are marked by signs and lane text such as “BUS ONLY” or “BUS LANE”; obey any posted operating hours, and do not drive, stop, or park in them except where signs permit entry, usually for turns. In states with yield‑to‑bus laws, let a bus signal and re‑enter traffic from a signed stop."""
